
language: csharp
dist: bionic
mono: none
dotnet: 2.2.0
script:
  - cd netcore2.2\netcore2.2
  - dotnet restore
  - dotnet build
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
    - DOTNET_CLI_TELEMETRY_OPTOUT=1