
language: csharp
dist: trusty
mono: none
dotnet: 2.0.0
script:   
  -if [$TRAVIS_BRANCH == "develop"]; then cd netcoredemo; fi
  -if [$TRAVIS_BRANCH == "develop"]; then dotnet restore; fi
  -if [$TRAVIS_BRANCH == "develop"]; then dotnet build; fi      
